### ISSUE TITLE
Error occasionally accessing _cachedsystemanimationfence requires the main thread ios

### ISSUE THREAD

**Issue by hiyshamx** [MOLPay/molpay-mobile-xdk-reactnative-beta#7] opened 2017-08-17 17:51 UTC
I'm having error as below in IOS 10.0. 

![screen shot 2017-08-18 at 1 50 12 am](https://user-images.githubusercontent.com/6882177/29425948-9c42f73c-83b7-11e7-8c3b-7a71d94edc82.png)

**Comment by LeowWH** [comment] 2017-08-17 23:52
Hi @nikhiysham,

We cannot reproduce your issue using the latest react-native 0.47.1 in iOS 10.3(simulator), iOS 10.0(simulator) and iOS 10.2(iPhone-5). Can you try to create a new project and follow the our molpay-mobile-xdk-reactnative-beta installation guide again. And for your information currently babel-preset-react-native 3.0.0 will have some issue if you create a new project so you can change it back to 2.1.0 in your package.json and remove the babel-preset-react-native folder and npm install again to solve it.

Thanks.

**Comment by hiyshamx** [comment] 2017-08-18 07:41
I'm using babel-preset-react-native": "1.9.2" anyway. Do i need to upgrade to 2.1.0 ? I found some thread relating to the same issue in https://github.com/wkh237/react-native-fetch-blob/issues/168 . 

By adding  `dispatch_get_main_queue()` in setPaymentDetails, it seems like the problem gone away

     dispatch_sync(dispatch_get_main_queue(), ^{
             [[UIApplication sharedApplication].keyWindow.rootViewController presentViewController:nc   
              animated:YES completion:nil];
     });

**Comment by clewlb** [comment] 2017-08-18 07:51
@nikhiysham,

Please close this issue if you're problem is resolved.

Thanks.

**Closed as completed** 2017-08-18 08:25 UTC
